services:
  postgres_auth_service:
    image: postgres:16
    environment:
      - 'POSTGRES_DB=authserver'
      - 'POSTGRES_PASSWORD=authserversecret!'
      - 'POSTGRES_USER=authserver'
    ports:
      - '5434:5432'
    restart: unless-stopped
