spring:
  docker:
    compose:
      lifecycle-management: start_only
  application:
    name: auth-server
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/authserver}
    username: ${SPRING_DATASOURCE_USERNAME:authserver}
    password: ${SPRING_DATASOURCE_PASSWORD:authserversecret}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  logging:
    pattern:
      correlation: '[%X{traceId:-}-%X{spanId:-}] [%X{tenantId:-}] '

server:
  port: 8083
