spring:
  docker:
    compose:
      lifecycle-management: start_only
  application:
    name: auth-server
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/authserver}
    username: ${SPRING_DATASOURCE_USERNAME:authserver}
    password: ${SPRING_DATASOURCE_PASSWORD:authserversecret!}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
    schema: public

logging:
  pattern:
    correlation: '[%X{traceId:-}-%X{spanId:-}] [%X{tenantId:-}] '

server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: bookanddrive!
    key-alias: myapp

jwt:
  secret: quBpmybUJ8U1cFc+9AevnmWg70OoJhxkAEWoY1iSOVwXXKn/QPG12OMm3z1iPSi7BvN6QzCwQaHFXW3TEtUBHxnbrMNMQgvZo6g4y1LGbPizPGnGnLGYLRJyQLJomX0KWJpexbACd0NkMlIe3QxoxTIfX/9kbCyxMgar28Mb5IqNpu7xXYXNSRKkujUj0T1T9/5RTmSKRYVwpjmq0JumTuG3MH9RwPe/y0omblAlo8eNXJVph1m396xjgZqrdBXiwk9QJJF88FubtByNaCZeNCbw0UjQ3gnlocW939ML2D6Zknp6gm8nXFbmuSRRDHgFxTUBP68/sCMk2J9gZgCwDMMpEU5BPpuXhWobDTjsJqI=
  token-lifespan: 3600000

multitenancy:
  http:
    header: X-Tenant-Id

admin-user:
  tenant: ${ADMIN_TENANT:superadmin}
  username: ${ADMIN_USERNAME:jakub@admin.com}
  roles: ${ADMIN_USER_ROLES_ARRAY:[SUPER_ADMIN, USERS_WRITE, USERS_READ, TENANTS_WRITE, TENANTS_READ]}

  mail:
    host: ${GMAIL_HOST:smtp.gmail.com}
    port: ${GMAIL_PORT:587}
    username: ${RESET_PASSWORD_GMAIL_USERNAME:bookanddrive.bad@gmail.com}
    password: ${RESET_PASSWORD_GMAIL_APP_PASSWORD:jsnc qzzx bukc usjb}
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
