name: Maven Build

# This workflow will be triggered for pull requests and pushes to specific branches
on:
  pull_request:
    branches:
     - 'feat/BOO*'
  push:
    branches:
      - main           # Trigger on direct pushes to the main branch
      - 'feat/BOO*'   # Trigger on pushes to branches that start with "feat/PLAT"

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use other OS runners, like macos-latest or windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Set the Java version to 23
          distribution: 'corretto'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository  # Path to the local Maven cache
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Cache key based on the pom.xml
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven build
        run: mvn clean install

